// Copyright (C) 2026 Mihawk-99
// SPDX-License-Identifier: GPL-3.0-or-later
#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) uniform sampler2D source_image;
layout(set = 1, binding = 0, rgba8) uniform writeonly image2D destination_image;
void main()
{
    ivec2 at = ivec2(gl_GlobalInvocationID.xy);
    imageStore(destination_image, at, texelFetch(source_image, at, 0).bgra);
}
